version: '3.7'
services:
  database:
    image: postgres:14.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: erutus91
      POSTGRES_USER: rotar
      container_name: mb
    ports:
      - "5444:5432"
    volumes:

      - ./createdb.sh:/docker-entrypoint-initdb.d/create_CREATE SEQUENCE hibernate_sequence START 1;createdb.sh
  weathermonitoring:
    image: weather
    build: ./
    ports:
      - "8082:8082"
    depends_on:
      - database

volumes:
  apps-volumes: